"""empty message

Revision ID: 05c41d06731b
Revises: ad8fc29e5a1f
Create Date: 2019-09-02 20:58:39.197821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c41d06731b'
down_revision = 'ad8fc29e5a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
